version: "3"
volumes:
  api_node_modules:

services:
  # system-api:
  #   build:
  #     context: Dockerfile.dev
  #   container_name: system-api
  #   ports:
  #     - "8080:8080"

  # etcd 참고
  # https://github.com/etcd-io/etcd/releases
  etcd:
    image: "gcr.io/etcd-development/etcd:v3.4.22"
    container_name: etcd
    ports:
      # - 4001:4001
      - 2380:2380
      - 2379:2379
    # environment:
    #   HostIP: "192.168.12.50"
    command: bash -c "
      /usr/local/bin/etcd \
      --name s1 \
      --data-dir /etcd-data \
      --listen-client-urls http://0.0.0.0:2379 \
      --advertise-client-urls http://0.0.0.0:2379 \
      --listen-peer-urls http://0.0.0.0:2380 \
      --initial-advertise-peer-urls http://0.0.0.0:2380 \
      --initial-cluster s1=http://0.0.0.0:2380 \
      --initial-cluster-token tkn \
      --initial-cluster-state new \
      --log-level info \
      --logger zap \
      --log-outputs stderr
      "
# rm -rf /tmp/etcd-data.tmp && mkdir -p /tmp/etcd-data.tmp && \
#   docker rmi gcr.io/etcd-development/etcd:v3.4.22 || true && \
#   docker run \
#   -p 2379:2379 \
#   -p 2380:2380 \
#   --mount type=bind,source=/tmp/etcd-data.tmp,destination=/etcd-data \
#   --name etcd-gcr-v3.4.22 \
#   gcr.io/etcd-development/etcd:v3.4.22 \
#   /usr/local/bin/etcd \
#   --name s1 \
#   --data-dir /etcd-data \
#   --listen-client-urls http://0.0.0.0:2379 \
#   --advertise-client-urls http://0.0.0.0:2379 \
#   --listen-peer-urls http://0.0.0.0:2380 \
#   --initial-advertise-peer-urls http://0.0.0.0:2380 \
#   --initial-cluster s1=http://0.0.0.0:2380 \
#   --initial-cluster-token tkn \
#   --initial-cluster-state new \
#   --log-level info \
#   --logger zap \
#   --log-outputs stderr

# docker exec etcd-gcr-v3.4.22 /bin/sh -c "/usr/local/bin/etcd --version"
# docker exec etcd-gcr-v3.4.22 /bin/sh -c "/usr/local/bin/etcdctl version"
# docker exec etcd-gcr-v3.4.22 /bin/sh -c "/usr/local/bin/etcdctl endpoint health"
# docker exec etcd-gcr-v3.4.22 /bin/sh -c "/usr/local/bin/etcdctl put foo bar"
# docker exec etcd-gcr-v3.4.22 /bin/sh -c "/usr/local/bin/etcdctl get foo"
